#ifndef REP_MOTIONDATA_REPLICA_H
#define REP_MOTIONDATA_REPLICA_H

// This is an autogenerated file.
// Do not edit this file, any changes made will be lost the next time it is generated.

#include <QtCore/qobject.h>
#include <QtCore/qdatastream.h>
#include <QtCore/qvariant.h>
#include <QtCore/qmetatype.h>

#include <QtRemoteObjects/qremoteobjectnode.h>
#include <QtRemoteObjects/qremoteobjectpendingcall.h>
#include <QtRemoteObjects/qremoteobjectreplica.h>


class MotionDataReplica : public QRemoteObjectReplica
{
    Q_OBJECT
    Q_CLASSINFO(QCLASSINFO_REMOTEOBJECT_TYPE, "MotionData")
    Q_CLASSINFO(QCLASSINFO_REMOTEOBJECT_SIGNATURE, "75af259929695e8568e278221155e9999222e7d3")
    Q_PROPERTY(QByteArray data READ data NOTIFY dataChanged)

public:
    enum NodePort {
        Default = 9529,
    };
#if (QT_VERSION >= QT_VERSION_CHECK(5, 5, 0))
    Q_ENUM(NodePort)
#else
    Q_ENUMS(NodePort)
#endif

public:
    MotionDataReplica() : QRemoteObjectReplica() { initialize(); }
    static void registerMetatypes()
    {
        static bool initialized = false;
        if (initialized)
            return;
        initialized = true;
    }

private:
    MotionDataReplica(QRemoteObjectNode *node, const QString &name = QString())
        : QRemoteObjectReplica(ConstructWithNode)
    {
        initializeNode(node, name);
    }

    void initialize() override
    {
        MotionDataReplica::registerMetatypes();
        QVariantList properties;
        properties.reserve(1);
        properties << QVariant::fromValue(QByteArray());
        setProperties(properties);
    }

public:
    virtual ~MotionDataReplica() {}

    static inline NodePort toNodePort(quint16 i, bool *ok = 0)
    {
        if (ok)
            *ok = true;
        switch (i) {
        case 9529: return Default;
        default:
            if (ok)
                *ok = false;
            return Default;
        }
    }
    QByteArray data() const
    {
        const QVariant variant = propAsVariant(0);
        if (!variant.canConvert<QByteArray>()) {
            qWarning() << "QtRO cannot convert the property data to type QByteArray";
        }
        return variant.value<QByteArray >();
    }


Q_SIGNALS:
    void dataChanged(QByteArray data);

private:
    friend class QT_PREPEND_NAMESPACE(QRemoteObjectNode);
};

#if (QT_VERSION < QT_VERSION_CHECK(5, 5, 0))
    Q_DECLARE_METATYPE(MotionDataReplica::NodePort)
#endif

inline QDataStream &operator<<(QDataStream &ds, const MotionDataReplica::NodePort &obj)
{
    quint16 val = obj;
    ds << val;
    return ds;
}

inline QDataStream &operator>>(QDataStream &ds, MotionDataReplica::NodePort &obj) {
    bool ok;
    quint16 val;
    ds >> val;
    obj = MotionDataReplica::toNodePort(val, &ok);
    if (!ok)
        qWarning() << "QtRO received an invalid enum value for typeNodePort, value =" << val;
    return ds;
}


QT_BEGIN_NAMESPACE
QT_END_NAMESPACE


#endif // REP_MOTIONDATA_REPLICA_H
